//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BigTrees
{
    using System;
    using System.Collections.Generic;
    
    public partial class treesTrunc
    {
        [System.ComponentModel.DataAnnotations.Key]
        public int ogr_fid { get; set; }
        public Nullable<decimal> obj_idnr { get; set; }
        public string kommun { get; set; }
        public string lokalnamn { get; set; }
        public string tradslag { get; set; }
        public Nullable<decimal> stamomkret { get; set; }
        public string tradstatus { get; set; }
        public Nullable<decimal> latitude { get; set; }
        public Nullable<decimal> longitude { get; set; }
    }
}
